name: PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup ganache-cli
      run: npm install -g ganache-cli

    - name: Install dependencies
      run: composer install --no-progress  

    - name: Copy configuration file
      run: cp phpunit.example.xml phpunit.xml

    - name: Run test suite
      run: |
        ganache-cli &
        sleep 5
        composer run-script tests

        
